int _putchar(char c);
void print_alphabet(void);
void print_alphabet_x10(void);
int _islower(int c);
void _isalpha(int);
void print_sign(int);
int _abs(int);
int print_last_digit(int);
int jack_bauer(void);
int times_table(void);
int add(int,int);
void print_to_98(int);
void print_times_table(int);
